# Generated by Django 4.2.3 on 2023-09-04 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('horario', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('telefono2', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10)),
                ('cuenta', models.CharField(max_length=100)),
                ('cpe', models.IntegerField()),
                ('chofer', models.CharField(max_length=100)),
                ('grano', models.CharField(max_length=10)),
                ('humedad_chasis', models.CharField(max_length=5)),
                ('humedad_acoplado', models.CharField(max_length=5)),
                ('promedio', models.CharField(max_length=5)),
                ('bruto', models.IntegerField()),
                ('tara', models.IntegerField()),
                ('neto', models.IntegerField()),
                ('observacion', models.CharField(max_length=250)),
                ('ticket', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportista', models.CharField(max_length=100)),
                ('cuit_transporte', models.IntegerField()),
                ('chofer', models.CharField(max_length=100)),
                ('cuit_chofer', models.IntegerField()),
                ('patente_chasis', models.CharField(max_length=10)),
                ('tecnica_chasis', models.CharField(max_length=10)),
                ('ruta_chasis', models.CharField(max_length=10)),
                ('seguro_chasis', models.CharField(max_length=10)),
                ('patente_acoplado', models.CharField(max_length=10)),
                ('tecnica_acoplado', models.CharField(max_length=10)),
                ('ruta_acoplado', models.CharField(max_length=10)),
                ('seguro_acoplado', models.CharField(max_length=10)),
                ('seguro_carga', models.CharField(max_length=10)),
                ('importe', models.CharField(max_length=10)),
                ('licencia', models.CharField(max_length=10)),
                ('psicofisico', models.CharField(max_length=10)),
                ('cuota_sindical', models.CharField(max_length=10)),
                ('art', models.CharField(max_length=10)),
                ('seguro_vida', models.CharField(max_length=10)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papeles',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10)),
                ('sucursal', models.CharField(max_length=15)),
                ('cuenta', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=5)),
                ('ubicacion', models.CharField(max_length=500)),
                ('transportista', models.CharField(max_length=100)),
                ('cumplimiento', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10)),
                ('grano', models.CharField(max_length=10)),
                ('cupo', models.CharField(max_length=100)),
                ('cpe', models.IntegerField()),
                ('transportista', models.CharField(max_length=100)),
                ('bruto', models.IntegerField()),
                ('tara', models.IntegerField()),
                ('neto', models.IntegerField()),
                ('observacion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportista', models.CharField(max_length=100)),
                ('cuit_transporte', models.IntegerField()),
                ('chofer', models.CharField(max_length=100)),
                ('cuit_chofer', models.IntegerField()),
                ('patente_chasis', models.CharField(max_length=10)),
                ('patente_acoplado', models.CharField(max_length=10)),
                ('observacion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
